# Chisimba reverse-proxy HTTPS compatibility.
# Author/Developer: Derek Keats
SetEnvIf X-Forwarded-Proto "^https$" HTTPS=on
SetEnvIf X-Forwarded-Proto "^https$" REQUEST_SCHEME=https
SetEnvIf X-Forwarded-Port "^8443$" SERVER_PORT=8443
