#!/usr/bin/env bash

set -Eeuo pipefail

ROOT="/run/media/derek/main/chisimba-revival"
DEV="${ROOT}/dev-environment"

FRAMEWORK="${ROOT}/framework/app"
INSTALLER="${FRAMEWORK}/installer"

PASS="${DEV}/tools/php-moderniser/modernise-legacy-constructors.php"
REBUILD="${DEV}/scripts/rebuild-runtime.sh"
COMPOSE="${DEV}/compose/php82.yml"
LOG="${ROOT}/killme.txt"

exec > >(tee "${LOG}") 2>&1

section()
{
    echo
    echo "============================================================"
    echo "$1"
    echo "============================================================"
}

fail()
{
    echo
    echo "ERROR: $*" >&2
    exit 1
}

section "Milestone 8: Recover and scope legacy-constructor pass"

echo "Started: $(date --iso-8601=seconds)"

for required in \
    "${FRAMEWORK}" \
    "${INSTALLER}" \
    "${PASS}" \
    "${REBUILD}" \
    "${COMPOSE}"
do
    [[ -e "${required}" ]] ||
        fail "Required path does not exist: ${required}"
done

section "Remove abandoned temporary files"

find "${FRAMEWORK}" \
    -type f \
    -name '*.legacy-constructor-moderniser.tmp' \
    -print \
    -delete

section "Remove only wrappers generated by the broad pass"

python3 - "${FRAMEWORK}" <<'PY'
from pathlib import Path
import re
import sys

root = Path(sys.argv[1])

extensions = (
    ".php",
    ".inc",
    ".inc.php",
)

pattern = re.compile(
    r'(?m)'
    r'^(?P<indent>[ \t]*)/\*\*\n'
    r'(?P=indent) \* PHP 8 constructor wrapper for the legacy '
    r'(?P<legacy>[A-Za-z_][A-Za-z0-9_]*)\(\) constructor\.\n'
    r'(?P=indent) \*/\n'
    r'(?P=indent)public function __construct\(\)\n'
    r'(?P=indent)\{\n'
    r'(?P=indent)    call_user_func_array\(\n'
    r"(?P=indent)        \[\$this, '(?P=legacy)'\],\n"
    r'(?P=indent)        func_get_args\(\)\n'
    r'(?P=indent)    \);\n'
    r'(?P=indent)\}\n\n'
)

changed_files = 0
removed_wrappers = 0

for path in root.rglob("*"):
    if not path.is_file():
        continue

    name = path.name.lower()

    if not any(name.endswith(extension) for extension in extensions):
        continue

    try:
        original = path.read_text()
    except UnicodeDecodeError:
        continue

    updated, count = pattern.subn("", original)

    if count == 0:
        continue

    path.write_text(updated)
    changed_files += 1
    removed_wrappers += count

    print(f"RESTORED ({count}): {path}")

print()
print(f"Files restored: {changed_files}")
print(f"Generated wrappers removed: {removed_wrappers}")
PY

section "Confirm broad generated wrappers are gone"

REMAINING="$(
    grep -RIl \
        --include='*.php' \
        --include='*.inc' \
        --include='*.inc.php' \
        'PHP 8 constructor wrapper for the legacy' \
        "${FRAMEWORK}" \
        || true
)"

if [[ -n "${REMAINING}" ]]; then
    echo "${REMAINING}"
    fail "Generated broad-pass wrappers remain."
fi

echo "All broad-pass generated wrappers were removed."

section "Preserve manually established InstallWizard constructor"

INSTALLWIZARD="${INSTALLER}/installwizard.inc"

COUNT="$(
    grep -Ec \
        'function[[:space:]]+__construct[[:space:]]*\(' \
        "${INSTALLWIZARD}"
)"

echo "InstallWizard __construct() count: ${COUNT}"

if [[ "${COUNT}" -ne 1 ]]; then
    fail "InstallWizard should retain exactly one constructor wrapper."
fi

section "Dry-run constructor pass on installer only"

php "${PASS}" \
    --dry-run \
    "${INSTALLER}"

section "Apply constructor pass to installer only"

php "${PASS}" \
    --apply \
    "${INSTALLER}"

section "Verify installer pass is idempotent"

SECOND_RUN="$(
    php "${PASS}" \
        --dry-run \
        "${INSTALLER}"
)"

printf '%s\n' "${SECOND_RUN}"

if ! grep -q 'Constructor wrappers: 0' <<<"${SECOND_RUN}"; then
    fail "Installer constructor pass is not idempotent."
fi

echo "Installer constructor pass is idempotent."

section "Verify Template constructor"

TEMPLATE="${INSTALLER}/template.inc"

grep -n -A20 -B5 \
    -E 'class[[:space:]]+Template|function[[:space:]]+(__construct|Template)' \
    "${TEMPLATE}"

if ! grep -Eq \
    'function[[:space:]]+__construct[[:space:]]*\(' \
    "${TEMPLATE}"
then
    fail "Template did not receive a PHP 8 constructor."
fi

section "List installer files changed"

git -C "${ROOT}/framework" status --short -- app/installer

section "Rebuild fresh PHP 8.2 runtime"

"${REBUILD}" php82 --fresh-db

section "Request installer"

sleep 3

set +e

HTTP_OUTPUT="$(
    curl \
        --silent \
        --show-error \
        --location \
        --max-time 30 \
        --write-out '\nHTTP_STATUS:%{http_code}\n' \
        "http://localhost:8082/ch/" \
        2>&1
)"

CURL_STATUS=$?

set -e

echo "curl exit status: ${CURL_STATUS}"
echo
printf '%s\n' "${HTTP_OUTPUT}"

section "First failure after scoped constructor pass"

PAGE_FAILURES="$(
    printf '%s\n' "${HTTP_OUTPUT}" \
    | grep -Ei \
        'fatal error|uncaught|typeerror|valueerror|parse error|compile error' \
    | head -n 30 \
    || true
)"

LOG_FAILURES="$(
    docker compose \
        -f "${COMPOSE}" \
        logs --no-color --since=2m web \
        2>/dev/null \
    | grep -Ei \
        'fatal error|uncaught|typeerror|valueerror|parse error|compile error' \
    | head -n 30 \
    || true
)"

if [[ -n "${PAGE_FAILURES}" ]]; then
    echo "--- Browser response ---"
    printf '%s\n' "${PAGE_FAILURES}"
fi

if [[ -n "${LOG_FAILURES}" ]]; then
    echo
    echo "--- Container log ---"
    printf '%s\n' "${LOG_FAILURES}"
fi

if [[ -z "${PAGE_FAILURES}" && -z "${LOG_FAILURES}" ]]; then
    echo "No fatal-pattern line was detected."
fi

section "Installer page indicators"

printf '%s\n' "${HTTP_OUTPUT}" \
    | grep -Ei \
        'chisimba|installer|welcome|licence|step|fatal error|warning' \
    | head -n 100 \
    || true

section "Recent PHP 8.2 log"

docker compose \
    -f "${COMPOSE}" \
    logs --no-color --tail=120 web \
    || true

section "Framework status summary"

git -C "${ROOT}/framework" status --short

section "Scoped constructor recovery complete"

echo "Finished: $(date --iso-8601=seconds)"
echo
echo "The reusable constructor pass remains available:"
echo "  ${PASS}"
echo
echo "It has currently been applied only to:"
echo "  ${INSTALLER}"
echo
echo "PHP 8.2:"
echo "  http://localhost:8082/ch/"
echo
echo "Upload:"
echo "  ${LOG}"
